### ISSUE TITLE
Duration prop validator

### ISSUE THREAD

**Issue by W1LLSON** [ps-cristopher/vue3-autocounter#10]
Hi. I need to set duration to 0.5, but I get a warning that the property failed validation. I understand that it is not allowed to set the value less than 1, but it is not written anywhere. 
Can you fix this please ?

**Comment by Tireur2cables** [comment]
Hi, I have the same 'issue' than @W1LLSON.
I have seen in the documentation that a decimal positive is a valid value and indeed it seems to work as it seems faster when I put .5 than when I put 1.
But I still have the warning about the validation of the property duration.
It maybe an old validation trigger from a time when decimals weren't supported.

**Comment by ps-cristopher** [comment]
Hi!, thanks for reporting it, I'll take a look. Also, please feel free to make a PR to fix this if you already know how to do it. PR's are open and welcome :)

**Comment by ps-cristopher** [comment]
There is an available update with this fixed on the last release: v1.0.7. This is closed.
