### ISSUE TITLE
start counter when it is visible

### ISSUE THREAD

**Issue by mahramane** [ps-cristopher/vue3-autocounter#6]
hi 
how can i start the counter when scrolling to the part where the counter is inside?
please help me

**Comment by mahramane** [comment]
I mean, when scrolling to the part where the counter is inside, the counter will start.

**Comment by ps-cristopher** [comment]
This is not an issue or a viable feature for the current version of the component but I can give you some support. You can create a ref for the `<vue3-autocounterref="counter" />` component and then you'll have access to the methods 'start()' , `pause()`, `resume()` and `reset()`, as is showed in the documentation. 

https://vue3autocounter.cristopherps.dev/docs#methods

To execute the `start()` method when the counter is visible you may need to use the Intersection Observer API which is a native web API. 

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

You can find some examples integrating the API with Vue 3, also you could find and use some wrapper vue3 components of the API to achieve it as well. 

Hope that helps. I'll close this issue.

**Comment by faridsa** [comment]
I know it's an old question but I think that an answer could be useful for future references.

The answer on how to start counter when enter in viewport using intersection observer API is in this blog post: [https://www.michaelsynan.com/blog/intersection-observer-nuxt](https://www.michaelsynan.com/blog/intersection-observer-nuxt)
